##
## EPITECH PROJECT, 2024
## B-YEP-400-MPL-4-1-zappy-thomas.janiaut
## File description:
## Makefile
##

SRC = main.py
DEST = ../zappy_ai

all: $(DEST)

$(DEST): $(SRC)
	chmod +x $(SRC)
	cp $(SRC) $(DEST)

clean:
	rm -f $(DEST)

fclean: clean

re: fclean all
